### ISSUE TITLE
List records for a domain parameters

### ISSUE THREAD

**Issue by tfarina** [dnsimple/dnsimple-developer#103]
https://github.com/dnsimple/dnsimple-developer/blob/master/content/v1/domains/records.markdown list "name" and "type" as parameters for GET /domains/:domain/records, but that does not make sense. Only ":domain" is required for listing records.

**Comment by weppos** [comment]
That's correct, `:domain` is the only required parameter. The other 2 parameters are query string parameters you can use to refine the query.

**Comment by tfarina** [comment]
That is interesting, but not obvious from reading the documentation. Do you think this information could be added to the doc somehow or be made more explicit in some other way?

Feel free to close this in any case though.

**Comment by weppos** [comment]
I'll leave the case open for now as we use the same approach also in API v2 documentation, and we may want to find a way to make it more clear.

**Comment by 3flex** [comment]
Might just be a matter of splitting path parameters and query parameters into separate sections? Something like this:

### Parameters

#### Path parameters (required)

Name | Type | Description
-----|------|------------
`:domain` | `string`, `integer` | The domain name or id

#### Query parameters
Name | Type | Description
-----|------|------------
`name` | `string` | The name to search for. Example: `www`
`type` | `string` | The record type to search for. Example: `www`

**Comment by weppos** [comment]
Closed by #174
