### ISSUE TITLE
API v2 docs report different zones for listZoneRecords call

### ISSUE THREAD

**Issue by nesQuick** [dnsimple/dnsimple-developer#107]
If I understood it correctly then listZoneRecords should return all records per zone, but in the following example it lists two zones: `zone_id: "example.com"` and `zone_id: "example-1458642023.com"`.

<img width="714" alt="screen shot 2016-11-24 at 22 45 06" src="https://cloud.githubusercontent.com/assets/584259/20610314/ee03dba0-b297-11e6-8e46-ef805d1ca4ba.png">

**Comment by jacegu** [comment]
That is odd. Hopefully it's simply a problem with the fixture...
