### ISSUE TITLE
Update fixtures downloading changes from /developer site

### ISSUE THREAD

**Issue by weppos** [dnsimple/dnsimple-developer#112]
Before the release, we should make sure that all the clients uses the same (and latest) version of the fixtures.

Ideally, we should have a task in each single repo that pulls the entire fixture folder and replaces the one in the client repo.

## Clients

- [x] Elixir (dnsimple/dnsimple-elixir#85)
- [x] Go
- [x] Node
- [x] Ruby (dnsimple/dnsimple-ruby#142)

**Comment by weppos** [comment]
I suggest to complete this task as a final one.

**Comment by jodosha** [comment]
Agree.

**Comment by weppos** [comment]
I am now going through  all the clients for a final update.

**Comment by weppos** [comment]
It was quite a bit of work.

**Comment by weppos** [comment]
Completed.
