### ISSUE TITLE
Clarify web hook reliability

### ISSUE THREAD

**Issue by OleMchls** [dnsimple/dnsimple-developer#127]
Currently the docs say:

```
Responding to Webhooks

To confirm receipt of a webhook, your server must respond with an HTTP 200 response. Any other response will be considered an error and may cause the event to be retried.
```

I think it would be more precise if a web hook is retried or not. _may_ may be problematic ;)

**Comment by sabran145** [comment]
on issu

**Comment by weppos** [comment]
@OleMchls I am assigning this ticket to you, to review the current notifier behavior and update the docs accordingly.
