### ISSUE TITLE
Document error responses

### ISSUE THREAD

**Issue by 3flex** [dnsimple/dnsimple-developer#133]
When sending an invalid request to create a new record, we might get an "errors" element in the JSON response:
```json
{
  "message": "Validation failed",
  "errors": {
    "record_type": [
      "can't be blank",
      "unsupported"
    ],
    "name": [
      "must be valid"
    ],
    "content": [
      "can't be blank"
    ]
  }
}
```

The "errors" element isn't documented. Appears to be field level validation, but it's not clear which endpoints will return this, and the format isn't specified in the documentation.

**Comment by jacegu** [comment]
Hey @3flex! Thanks for reporting this. It was about time we got back to you on it... 😅

Even though we will continue to improve the error documentation, here are some things we have improved:
- We have documented the error responses in our [OpenAPI specification](https://github.com/dnsimple/dnsimple-developer/blob/main/content/v2/openapi.yml) 
  #426 
- We have improved our error section in the API overview, including examples of the different response formats for each HTTP error code. These have been linked from the each endpoint's documentation. Improving and completing this information will be an ongoing effort
  #425 

Hopefully that will help. If there is anything you miss, feel free to reopen this issue (or open a more specific one). Thanks again for your suggestion. 😊
