### ISSUE TITLE
Publish API via swagger?

### ISSUE THREAD

**Issue by solvingJ** [dnsimple/dnsimple-developer#138]
Need sdks for several languages you don't have. Just want to recommend moving to swagger in case it's not been discussed yet.

**Comment by weppos** [comment]
We are considering to use OpenAPI to describe the API. However, I don't have an ETA yet.

We will publish more informations as soon as we've taken a decision. For now, I am going to close this ticket.

What language are you using that we don't provide an SDK for?

**Comment by solvingJ** [comment]
Great to hear!  C++ and .NET.
