### ISSUE TITLE
OAuth: DNSimple requires undocumented "state" parameter in token request

### ISSUE THREAD

**Issue by 3flex** [dnsimple/dnsimple-developer#140]
According to RFC 6749 "state" is only used in authorization request and authorization response. However in the DNSimple implementation (in the sandbox at any rate) it's required at step 2 as a POST parameter. This isn't in compliance with the spec, and also isn't documented in the DNSimple docs.

**Comment by weppos** [comment]
@3flex it's right, it looks like the RFC doesn't set the state as mandatory. We will have to review why we did (I'm sure there was a specific, but I don't recall it, I need to check back our internal notes).
