### ISSUE TITLE
Store the DNSimple cheatsheets PDF

### ISSUE THREAD

**Issue by weppos** [dnsimple/dnsimple-developer#144]
Store the PDF in this repo instead of via tweets.
https://twitter.com/CodeStars/status/845932130958032896

**Comment by sbastn** [comment]
They are in the Marketing repo: https://github.com/dnsimple/dnsimple-marketing/tree/master/artwork/cheatsheets

**Comment by sbastn** [comment]
You can download the Ruby cheatsheet from the API page: https://dnsimple.com/api. We need to add the NodeJS to that page as well
