### ISSUE TITLE
register / purchase domain w/ curl

### ISSUE THREAD

**Issue by nousacademy** [dnsimple/dnsimple-developer#145]
Is this correct for purchasing / registering a domain?

I get the response of:` {"message":"Validation failed"}`

`curl  -H 'Authorization: Bearer '$apiv2token -H 'Accept: application/json' -H 'Content-Type: application/json' -X POST -d '{"registrant_id": 72624, "whois_privacy":false, "auto_renew": true, "premium_price": false,"extended_attributes":"com", "premium_price":null}' https://api.dnsimple.com/v2/$acctId/registrar/domains/mydomain.com/registrations`

**Comment by jacegu** [comment]
You shouldn't be passing the `premium_price` unless you know the domain is, indeed, a premium domain. If it is, `premium_price` should be an string reflecting the premium price returned by our CheckDomainPremiumPrice endpoint: https://developer.dnsimple.com/v2/registrar/#premium-price, and not a boolean value.

If you want to know if a domain is premium, you can use the CheckDomainAvailability endpoint https://developer.dnsimple.com/v2/registrar/#check which returns this information.

Also, you don't need to pass extended attributes for all TLDs, only for certain ccTLDs that require it.

That said, the simplest, valid registration via curl should be something like:

```bash
curl -H 'Authorization: Bearer XXXXXXXXX' -H 'Accept: application/json' -H 'Content-Type: application/json' -X POST -d '{"registrant_id":  REGISTRANT_ID}' https://api.sandbox.dnsimple.com/v2/ACCOUNT_ID/registrar/domains/DOMAINTOREGISTER.COM/registrations
```

Note that I used our [sandbox environment](https://sandbox.dnsimple.com) which will allow you to test these type of commands without spending real money or causing issues to any of your domains.

**Comment by nousacademy** [comment]
Is it required to use 2FA ??

**Comment by jacegu** [comment]
No, it is not.

**Comment by nousacademy** [comment]
I'm having authentication issues, I updated my bash script : 

# twoFAToken = one time generated token

`curl -H 'Authorization: Bearer '$twoFAToken -H 'Accept: application/json' -H 'Content-Type: application/json' -X POST -d '{"registrant_id":  '$acctId'}' https://api.sandbox.dnsimple.com/v2/$acctId/registrar/domains/exampleyttyty.com/registrations`

Response:

`{"message":"Authentication failed"}`

**Comment by weppos** [comment]
@nousacademy please add `-i` flag and post the complete response you get.

**Comment by nousacademy** [comment]
`HTTP/1.1 401 Unauthorized
Server: nginx
Date: Mon, 01 May 2017 04:31:17 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-RateLimit-Limit: 30
X-RateLimit-Remaining: 30
X-RateLimit-Reset: 1493616677
Cache-Control: no-cache
X-Request-Id: 8554e954-8c5f-4838-8cc9-d3a4bdad6d19
X-Runtime: 0.013453
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: DENY
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 1; mode=block`

**Comment by weppos** [comment]
@nousacademy it looks like the token is incorrect, or not properly passed. Please write to support@dnsimple.com so that we can check with the real token.
