### ISSUE TITLE
Document X-RateLimit headers in the schema

### ISSUE THREAD

**Issue by weppos** [dnsimple/dnsimple-developer#526]
We have a number of mismatching/undocumented headers in our OpenAPI schema file:

<img width="468" alt="Screenshot 2023-09-06 at 12 14 49" src="https://github.com/dnsimple/dnsimple-developer/assets/5387/b068ac41-57de-4ad6-bf3a-f40a8744c814">

Truth to be told, our API returns more header than necessary (as we bundle some with the app as well). But that's a different conversation.

At minimum, for API-specific headers (like X-RateLimit), we should have them documented in the schema file.

**Comment by DXTimer** [comment]
I've added this to our board to look into during this cycle.

**Comment by DXTimer** [comment]
There is no elegant way to add headers to the spec it has to be done for each response. If we were to go ahead we would be adding approximately 400 new lines to document just the rate limit headers. It's not very common to document common headers. Would you still like to see the headers added to the spec?

To give an idea of what it looks like to document the headers:

```yaml
openapi: 3.0.1
info:
  title: API
  version: 1.0.0
paths:
  /:
    get:
      responses:
        '200':
          description: Successful Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          headers:
            'X-Total-Items':
               $ref: '#/components/headers/xTotalItems'
            'X-Total-Pages':
               $ref: '#/components/headers/xTotalPages'
components:
  schemas:
    User: {}
  headers:
    xTotalItems:
      schema:
        type: integer
        description: test
    xTotalPages:
      schema:
        type: integer
        description: test
```

**Comment by weppos** [comment]
Given the complexity, at this time I don't think we want to move forward. i recommend we reach out to the OpenAPI maintainers and file a enhancement request to define a reusable component as exists for other schema objects.

**Comment by DXTimer** [comment]
It doesn't appear that OAS 3.x will add support for the headers as a reference object, as the main focus is on the OAS 4 a.k.a. Moonwalk. One alternative approach we can take is to use YAML anchors to define common headers then the maintainer will have to render the YAML applying to anchors and producing a valid OpenAPI schema that will be treated as read-only by the maintainers and what we share and reference publicly.

```yaml
openapi: 3.0.1
info:
  title: API
  version: 1.0.0
paths:
  /:
    get:
      responses:
        '200':
          description: Successful Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          headers: *commonHeaders

components:
  schemas:
    User: {}

commonHeaders: &commonHeaders
    xTotalItems:
      schema:
        type: integer
        description: test
    xTotalPages:
      schema:
        type: integer
        description: test
```

Closing for now. If we choose to take any of the mentioned approaches we can revisit the issue.
