### ISSUE TITLE
Add example responses where they are missing

### ISSUE THREAD

**Issue by aeden** [dnsimple/dnsimple-developer#61]
- [x] https://developer.dnsimple.com/v2/zones/records/ (#68)
- [x] https://developer.dnsimple.com/v2/services/ (#65)
- [x] https://developer.dnsimple.com/v2/templates/  (bd16a14327e844917334ef5b504d5e60c5898873 and 0996fb4db2e41059137733d4161662dc197053e1)
- [x] https://developer.dnsimple.com/v2/templates/records/ (#67)
- [x] https://developer.dnsimple.com/v2/vanity/

**Comment by jacegu** [comment]
I have updated the description of the issue to track progress

**Comment by weppos** [comment]
Completed.
