### ISSUE TITLE
Missing payload example for POST and PATCH endpoints

### ISSUE THREAD

**Issue by jacegu** [dnsimple/dnsimple-developer#69]
Documentation for `POST` and `PATCH` actions include a section to display an example of a JSON payload. We have to complete that section in several places:

- [x] [`Domain.create`](https://developer.dnsimple.com/v2/domains/#create)
- [x] [`EmailForward.create`](https://developer.dnsimple.com/v2/domains/email-forwards/#create)
- [x] [`VanityNameServers.delegate`](https://developer.dnsimple.com/v2/registrar/delegation/#delegateToVanity)
- [x] [`Contacts.create`](https://developer.dnsimple.com/v2/contacts/#create)
- [x] [`ZoneRecords.create`](https://developer.dnsimple.com/v2/zones/records/#create) #68
- [x] [`ZoneRecords.update`](https://developer.dnsimple.com/v2/zones/records/#update) #68
- [x] [`TemplateRecords.create`](https://developer.dnsimple.com/v2/templates/records/#create)

**Comment by jacegu** [comment]
The example was removed altogether for the vanity name servers endpoint.

**Comment by jacegu** [comment]
I've gone over all the docs again and it looks like there are no more empty examples. Calling this fixed.

**Comment by weppos** [comment]
> I've gone over all the docs again and it looks like there are no more empty examples. Calling this fixed.

👏
